server:
  port: 3344

spring:
  application:
    name: springcloud-simple-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xsxlq/springcloudsimple-config.git

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
